### ISSUE TITLE
can't donwload with hub in colab

### ISSUE THREAD

**Issue by eikibw** [anxety-solo/sd-webui-anxety-colab#11]
i get error when downloading using hub extension

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 332, in downloader
    for _text, _flag in surface(command, token2, token3):
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 314, in surface
    for message, isError in gdrown(url, target_path, fn):
  File "/root/sdw/extensions/HUB/sd_hub/downloader.py", line 21, in gdrown
    p = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/gdown'

**Comment by anxety-solo** [comment]
I don't know why to create a problem with me and not the author of this extension. And yes I don't know why this happens.

**Comment by eikibw** [comment]
ah, it looks like I'm in the wrong place. I'm sorry.
